project_name: dhRate
env:
  - CGO_ENABLED=0
builds:
  - binary: dhrate
    id: dhrate
    main: ./
    ldflags:
      - -X main.VERSION={{ .Version }}
    targets:
      - darwin_amd64
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
    gobinary: "go1.17.4"
archives:
  - builds:
      - dhrate
    name_template: "dhrate-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
release:
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  header: |
    ## {{ .Version }} ({{ .Date }})
    New {{ .Version }} release!
  footer: |
    ## Release Notes
    Please read the [RELEASE_NOTES](https://github.com/allaman/dhrate/blob/master/RELEASE-NOTES.md) which contain among other things important information for who is upgrading from previous releases.
    ## Thanks!
